[package]
name = "trapez"
version = "0.1.0"
authors = ["André Rüdiger <andre.ruediger@gmail.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1.20", features = [ "rt-multi-thread", "sync", "macros" ] }
